source 'https://rubygems.org'

gem 'async', '~> 2.3.1'
gem 'async-http', '~> 0.59.4'
gem 'async-websocket', '~> 0.22.1'
gem 'digest', '~> 3.1.1'
gem 'uri', '~> 0.12.0'

group :test do
  gem 'minitest', '~> 5.17.0'
  gem 'dotenv', '~> 2.8.1'
end
