name: vaas-golang-ci
on:
  push:
    branches:
      - main
    paths:
      - "golang/vaas/**"
      - ".github/workflows/ci-golang.yaml"
    tags:
      - "go*"
  pull_request:
    branches:
      - main
    paths:
      - "golang/vaas/**"
      - ".github/workflows/ci-golang.yaml"
  workflow_dispatch:
  
jobs:
  build-golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up Golang
        uses: actions/setup-go@v4.0.1
        with:
          go-version: 1.20.5
          cache: true
          cache-dependency-path: golang/vaas/go.sum
      - name: run tests staging
        if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/go')
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.STAGING_CLIENT_SECRET }}
          VAAS_URL: "wss://gateway.staging.vaas.gdatasecurity.de"
          TOKEN_URL: "https://account-staging.gdata.de/realms/vaas-staging/protocol/openid-connect/token"
        run: go test ./...
        working-directory: golang/vaas/    
      - name: run tests
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/go')
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          VAAS_URL: "wss://gateway.production.vaas.gdatasecurity.de"
          TOKEN_URL: "https://account.gdata.de/realms/vaas-production/protocol/openid-connect/token"
        run: go test ./...
        working-directory: golang/vaas/
      - name: publish module
        if: startsWith(github.ref, 'refs/tags/go')
        run: GOPROXY=proxy.golang.org go list -m github.com/GDATASoftwareAG/vaas/golang/vaas@go${GITHUB_REF#refs/tags/go}
