name: git-scan
on:
  push:
    tags:
      - "git-scan*"
    paths:
      - "golang/vaas/**"
      - ".github/workflows/ci-git-scan.yaml"

jobs:
  build-git-scan:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan for Viruses
        uses: ./.github/actions/vaas-scan-action
        with:
          VAAS_CLIENT_ID: ${{ secrets.VAAS_SCAN_CLIENT_ID }}
          VAAS_CLIENT_SECRET: ${{ secrets.VAAS_SCAN_CLIENT_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/git-scan}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/gdatasoftwareag/vaas/git-scan
          tags: |
            type=semver,pattern={{version}},value=${{ env.RELEASE_VERSION }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.RELEASE_VERSION }}
            type=semver,pattern={{major}},value=${{ env.RELEASE_VERSION }}
          flavor: |
            latest=auto

      - name: login to ghcr.io/gdatasoftwareag
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_IO_GDATASOFTWAREAG_USERNAME }}
          password: ${{ secrets.GHCR_IO_GDATASOFTWAREAG_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "golang/vaas/"
          file: "golang/vaas/git-scan.Dockerfile"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
