name: vaas-ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-java:
    name: Build & Test Java SDK
    runs-on: ubuntu-20.04
    env:
      VAAS_TOKEN: ${{ secrets.VAAS_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: "7.2"

      - name: Run Java Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          gradle-version: "7.2"
          build-root-directory: java

  build-php:
    name: Build & Test PHP SDK
    runs-on: ubuntu-20.04
    env:
      VAAS_TOKEN: ${{ secrets.VAAS_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: install php dependencies
        uses: php-actions/composer@v6
        with:
          args: --working-dir php/tests/vaas

      - name: run tests
        run: ./vendor/bin/phpunit --colors --testdox
        working-directory: php/tests/vaas

  build-typescript:
    name: Build & Test TypeScript SDK
    runs-on: ubuntu-20.04
    env:
      VAAS_TOKEN: ${{ secrets.VAAS_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: install dependencies
        run: npm install
        working-directory: typescript

      - name: run Tests
        run: npm run test
        working-directory: typescript
