name: vaas-ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build-java:
    name: Build & Test Java SDK
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Java Tests
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: test
      

