name: vaas-ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build-java:
    name: Build & Test Java SDK
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.2'

      - name: Run Java Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          gradle-version: '7.2'
        working-directory: java
      

