name: Delete old container images

on:
  schedule:
    - cron: "15 * * * *" # run hourly

jobs:
  clean-ghcr:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./github-actions/cleanup-packages/...

      - name: Run go vet
        run: go vet ./github-actions/cleanup-packages/...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./github-actions/cleanup-packages/...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./github-actions/cleanup-packages/...

      - name: Run tests
        run: go test -race -vet=off ./github-actions/cleanup-packages/...

      - name: Delete Versions
        if: github.ref == 'refs/heads/main'
        run: go run ./github-actions/cleanup-packages/cmd/main.go
