name: Vulnerability Check

on:
  push:
    branches:
      - main
    paths:
      - "golang/vaas/**"
      - ".github/workflows/vulncheck-golang.yml"
    tags:
      - "go*"
  workflow_dispatch:

jobs:
  vulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.20.6
          cache: true
          cache-dependency-path: golang/vaas/go.sum
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
        shell: bash
      - name: Run govulncheck

        run: govulncheck ./...
        working-directory: golang/vaas/
        shell: bash

      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: failure()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          overwrite: "{title: `Failed workflow on for VaaS-SDK ${workflow}`, sections: [{activityTitle: 'build failed', activitySubtitle: `Failed workflow on for VaaS-SDK ${workflow}`, activityImage: 'https://adaptivecards.io/content/cats/3.png'}], themeColor: '#ff0000'}"
