name: Vulnerability Check

on: [push]

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v0.1.0
        with:
           go-version-input: 1.20.4
           go-package: ../../golang/vaas/...
